import type { CompiledProfile } from "./types";

export interface PersonaSeed {
  name: string;
  emoji: string;
  tagline: string;
  isBot: boolean;
  profile: CompiledProfile;
}

export const PERSONAS: PersonaSeed[] = [
  {
    name: "小柚",
    emoji: "🍊",
    tagline: "插畫家 · 重度社恐 · 貓奴",
    isBot: true,
    profile: {
      nickname: "小柚",
      ageRange: "26-29",
      city: "台北",
      jobField: "自由接案插畫家",
      vibe: "安靜但內心小劇場很多的創作者",
      interests: ["插畫", "貓", "二手書店", "手沖咖啡", "有聲書", "看海"],
      values: ["真誠", "創作自由", "溫柔的界線感"],
      lifestyle: "作息偏晚，一週大多在家畫圖，週末逛書店或窩咖啡廳",
      lookingFor: "先從舒服的筆友式慢溫開始，能安靜相處也不尷尬的人",
      commsStyle: "文字派，需要多一點時間回訊息，但回覆都很認真",
      dealbreakers: ["已讀不回催促", "吵雜的團體聚會壓力"],
      bio: "畫圖的人。家裡有兩隻貓主子。比起熱鬧，更喜歡一對一慢慢聊。",
    },
  },
  {
    name: "阿哲",
    emoji: "🏃",
    tagline: "後端工程師 · 健身 · 直球派",
    isBot: true,
    profile: {
      nickname: "阿哲",
      ageRange: "28-32",
      city: "新竹",
      jobField: "後端工程師",
      vibe: "講話很直但很好懂的工具人",
      interests: ["健身", "做菜", "露營", "科技新聞", "羽球", "看職籃"],
      values: ["效率", "誠實直接", "互相扶持"],
      lifestyle: "工程師作息，一週練三次 gym，假日喜歡往戶外跑",
      lookingFor: "認真交往，目標是一起變更好",
      commsStyle: "有話直說，不愛猜心，但答應的事一定做到",
      dealbreakers: ["冷戰", "講話一直曖昧不明"],
      bio: "寫程式也做自己的人生後端支援。會煮不錯的義大利麵。",
    },
  },
  {
    name: "佩琪",
    emoji: "☕",
    tagline: "行銷企劃 · E人 · 行程滿檔",
    isBot: true,
    profile: {
      nickname: "佩琪",
      ageRange: "27-31",
      city: "台北",
      jobField: "行銷企劃",
      vibe: "朋友很多但時間很少的社交冠軍",
      interests: ["爬山", "咖啡廳探店", "市集", "攝影", "音樂祭", "日劇"],
      values: ["成長", "生活體驗", "彼此獨立又支持"],
      lifestyle: "平日加班爆幹，假日行程滿到爆，效率至上",
      lookingFor: "合得來就能約的對象，希望對方有自己的生活",
      commsStyle: "語音訊息派，回訊快，講話自帶表情符號",
      dealbreakers: ["管太多", "沒有自己的興趣"],
      bio: "工作很忙但生活更忙。帶我去你私藏的咖啡廳，我帶你去爬山。",
    },
  },
  {
    name: "老吳",
    emoji: "🎷",
    tagline: "中學老師 · 慢熱 · 桌遊迷",
    isBot: true,
    profile: {
      nickname: "老吳",
      ageRange: "30-35",
      city: "台中",
      jobField: "中學歷史老師",
      vibe: "冷面笑匠，慢熱但很暖",
      interests: ["桌遊", "爵士樂", "紀錄片", "騎車亂晃", "歷史冷知識", "泡茶"],
      values: ["穩定", "幽默感", "互相尊重"],
      lifestyle: "規律上班族，晚上備課，週末桌遊聚會或騎車出遊",
      lookingFor: "可以一起安靜做事的長期關係，不急但認真",
      commsStyle: "文字為主，慢熱，熟了之後很會講冷笑話",
      dealbreakers: ["不尊重服務業", "價值觀差太多的政治極端"],
      bio: "歷史老師，相信慢一點的關係更持久。附贈冷笑話無限供應。",
    },
  },
  {
    name: "Momo",
    emoji: "🌙",
    tagline: "護理師 · 輪班 · 追劇擔當",
    isBot: true,
    profile: {
      nickname: "Momo",
      ageRange: "25-28",
      city: "高雄",
      jobField: "護理師",
      vibe: "輪班硬漢（？）其實是愛撒嬜的軟妹子",
      interests: ["追劇", "溫泉旅行", "甜點", "按摩放鬆", "Spotify 老歌", "睡到自然醒"],
      values: ["被理解", "休息品質", "小確幸"],
      lifestyle: "三班輪班，休假不定，居家常態但說走就走小型旅行",
      lookingFor: "能配合輪班作息、穩定溫柔的長期對象",
      commsStyle: "文字＋貼圖大戶，下班後是聊天黃金時段",
      dealbreakers: ["嫌我上班時間怪", "約會永遠要別人配合他"],
      bio: "白天救人晚上追劇。介紹一家好吃的甜點店給我，我們就成功了 50%。",
    },
  },
  {
    name: "Kevin",
    emoji: "🍳",
    tagline: "產品經理 · 路跑 · 廚藝中等",
    isBot: true,
    profile: {
      nickname: "Kevin",
      ageRange: "29-33",
      city: "台北",
      jobField: "科技業產品經理",
      vibe: "會做規劃也會做早餐的計畫控",
      interests: ["路跑", "做菜", "爵士鼓", "看展", "投資理財", "寵物狗"],
      values: ["誠懇溝通", "健康生活", "一起規劃未來"],
      lifestyle: "早起跑 5K 再上班，週末市場買菜煮飯，偶爾看展",
      lookingFor: "想認真交往，理想是一起生活節拍相近的伴",
      commsStyle: "喜歡約見面聊，線上聊天會認真回但偏慢",
      dealbreakers: ["完全沒有同理心", "生活習慣極端混亂"],
      bio: "PM 訓練出的壞習慣：什麼都想做規劃，包括下次約會。",
    },
  },
  {
    name: "恬恬",
    emoji: "🎸",
    tagline: "音樂治療師 · HSP · 露營吉他",
    isBot: true,
    profile: {
      nickname: "恬恬",
      ageRange: "24-27",
      city: "台南",
      jobField: "音樂治療師",
      vibe: "高敏感但溫柔堅定的療癒系",
      interests: ["吉他", "露營", "冥想", "手作", "聽黑膠", "貓", "星空"],
      values: ["情緒安全", "深度對話", "善待萬物"],
      lifestyle: "工作日在機構帶治療課，週末常往郊外露營充電",
      lookingFor: "能接住彼此情緒、願意深度聊天的長期夥伴",
      commsStyle: "一對一深聊很可以，團體場合需要暖機時間",
      dealbreakers: ["嘲笑別人的敏感", "約會遲到不說一聲"],
      bio: "音樂治療師。會記得你隨口說過的小事。營地吉他手，會點歌。",
    },
  },
];

// 預建的示範真人身分（不想走 onboarding 時可直接用）
export const DEMO_HUMAN: PersonaSeed = {
  name: "Demo小陽",
  emoji: "🐣",
  tagline: "示範身分 · 已建好月老檔案，可立即體驗配對",
  isBot: false,
  profile: {
    nickname: "小陽",
    ageRange: "27-30",
    city: "台北",
    jobField: "UI 設計師",
    vibe: "嘴上說宅但其實很會照顧人的細節控",
    interests: ["插畫", "看展", "手沖咖啡", "桌遊", "貓", "露營", "追劇", "投資理財"],
    values: ["真誠", "深度對話", "健康生活"],
    lifestyle: "平日上班畫稿，週末看展或窩咖啡廳，偶爾跟朋友露營",
    lookingFor: "認真交往，想找能一起安靜做事也一起冒險的人",
    commsStyle: "文字派，回訊穩定，喜歡分享生活小片段",
    dealbreakers: ["不尊重店員", "聊三次就消失"],
    bio: "設計師，貓派。可以陪你逛三小時美術館，也可以陪你宅一整天。",
  },
};
